ARG PGVERSION=17

FROM debian:bullseye-slim

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    gdb \
    git \
    gnupg \
    htop \
    jq \
    libgc1 \
    libpq5 \
    lsof \
    make \
    openssl \
    postgresql-client-common \
    psmisc \
    strace \
    sudo \
    tmux \
    watch \
  && rm -rf /var/lib/apt/lists/*

RUN curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN echo "deb http://apt.postgresql.org/pub/repos/apt bullseye-pgdg main ${PGVERSION}" > /etc/apt/sources.list.d/pgdg.list

# bypass initdb of a "main" cluster
RUN echo 'create_main_cluster = false' | sudo tee -a /etc/postgresql-common/createcluster.conf
RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    postgresql-${PGVERSION} \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/
RUN git clone --depth 1 https://github.com/devrimgunduz/pagila.git

#RUN adduser --disabled-password --gecos '' --home /var/lib/postgres docker
#RUN adduser docker sudo
RUN getent group | cut -d: -f1,3
RUN set -eux; \
	groupadd -r postgres --gid=999; \
# https://salsa.debian.org/postgresql/postgresql-common/blob/997d842ee744687d99a2b2d95c1083a2615c79e8/debian/postgresql-common.postinst#L32-35
	useradd -r -g postgres --uid=999 --home-dir=/var/lib/postgresql --shell=/bin/bash postgres; \
RUN getent group | cut -d: -f1,3
RUN sudo useradd -rm -d /var/lib/postgres -s /bin/bash -g postgres -G sudo docker
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

COPY --from=pgcopydb /usr/local/bin/sqlite3 /usr/local/bin
COPY --from=pgcopydb /usr/local/bin/pgcopydb /usr/local/bin

COPY .psqlrc /var/lib/postgres
COPY .sqliterc /var/lib/postgres
COPY cleanup.mk /var/lib/postgres
