ARG PGVERSION="17"

FROM debian:trixie-slim

RUN apt-get update \
  && apt-get install --fix-missing -y --no-install-recommends \
    ca-certificates \
    curl \
    gdb \
    git \
    gnupg \
    htop \
    jq \
    libgc1 \
    libpq5 \
    lsof \
    make \
    openssl \
    postgresql-17-wal2json \
    postgresql-client-common \
    postgresql-client-${PGVERSION} \
    postgresql-common \
    postgresql-server-dev-all \
    psmisc \
    strace \
    sudo \
    tmux \
    watch \
  && rm -rf /var/lib/apt/lists/*

RUN curl https://www.postgresql.org/media/keys/ACCC4CF8.asc > /tmp/ACCC4CF8.asc && \
    gpg --dearmor -o /usr/share/keyrings/postgresql-archive-keyring.gpg /tmp/ACCC4CF8.asc

RUN echo "deb [signed-by=/usr/share/keyrings/postgresql-archive-keyring.gpg] http://apt.postgresql.org/pub/repos/apt trixie-pgdg main ${PGVERSION}" > /etc/apt/sources.list.d/pgdg.list

# bypass initdb of a "main" cluster
RUN echo 'create_main_cluster = false' | sudo tee -a /etc/postgresql-common/createcluster.conf
RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    postgresql-${PGVERSION} \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/
RUN git clone --depth 1 https://github.com/devrimgunduz/pagila.git

#RUN adduser --disabled-password --gecos '' --home /var/lib/postgres docker
#RUN adduser docker sudo
RUN sudo useradd -rm -d /var/lib/postgres -s /bin/bash -g postgres -G sudo docker
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

COPY --from=pgcopydb /usr/local/bin/sqlite3 /usr/local/bin
COPY --from=pgcopydb /usr/local/bin/pgcopydb /usr/local/bin

COPY .psqlrc /var/lib/postgres
COPY .sqliterc /var/lib/postgres
COPY cleanup.mk /var/lib/postgres
