FROM postgres:17-bullseye

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
      postgresql-17-wal2json \
      postgresql-17-partman \
      postgresql-17-postgis-3 \
      postgis \
    && rm -rf /var/lib/apt/lists/*
